import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Navbar } from "../components/navbar";
import { Footer } from "../components/Footer";
import ContactForm from "../components/ContactForm";
import { Header } from "@/components/Header";
import AnimationBackground from "@/components/AnimationBackground";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "YoulivEvent",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer
          links={[
            { href: "/private_policy", label: "Politique de confidentialité" },
            { href: "/terms_of_services", label: "Conditions d'utilisations" },
          ]}
        />
      </body>
    </html>
  );
}
